version: '3.9'

services:
  auth_backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: auth-backend
    image: auth-backend:latest
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - mynetwork
  mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - mynetwork
volumes:
  db_data:
networks:
  mynetwork:
    driver: bridge

